language: java
deploy:
  provider: releases
  api_key:
    secure: Z/tp2PAKO45wqiNL7urpQwBUwZr3E/bf6f1ydhdb8l5yYtoGiCaHlsystozy483xuqX2gh/hghoxZqutQcwpssvDUMt6tRZQQLS6EJFl/Q/Za4//aSHKdisfvlmWFPRnNwe3JZucUnzeTa8GnJIOpkiJdA5w/kxP/YjI+6TypSPtv5YSIXppFMmHkPQj/H7cwK0lSCqwK6baGeNgzbaiiF1gFWbm9C62kswrJt15RcKW6yNqTbPyp1QQmYIBRM3gCzQRDYybdpEbw1jUg+nrwAkf8087b40+aaiot+JDp1gDYHSf1+jrAbfmyqz/UpxySf/ehlbzCBWE5wPETeC+rnBISowGN43qEIb/ET13TEm2wdFUcO7j0b0exhvaTEuGSGDPrt5g+yapiq1hi2lvCiGU7splNaV9LAh16B8AOlcXw24CRk24hm3J/ZtprCm+uiWBNVfqgIrPpZSDpkgcUCe3vRwjlWwIHt0w5bNwcU03pd4CPHWVzfw4MgFFa36yCVm7o4ARPL0jykOBNEDrrjPmuq5ieOG02oJ2ObZCmKi3I/b2dFc6He0l6PE+8SQUN7U2GAtyHNZTQzyH8EmqNjQd7WoqAnV8s4C8KwFnrfNbGCA7uGXhZ+v+ghl63Us8HQTyD45G/Brj1nVpDBtbrzvJaogjLWLwYdpBj9BBPAk=
  file: build/libs/xlr-conjur-plugin-1.0.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-conjur-plugin
